### ISSUE TITLE
totales_nacionales no se han actualizado

### ISSUE THREAD

**Issue by pcornejov** [Data-Observatory/covid19-API#16]
Estimados, desde la API el producto totales_nacionales devuelve hasta el 19 de junio.. lo podrian revisar?
Saludos

**Comment by scornejob** [comment]
claro @pcornejov . Nos puedes mostrar tu query?

**Comment by scornejob** [comment]
En realidad, tienes razon.

```
> select * from Totales_nacionales where time = '2020-06-19'
name: Totales_nacionales
time			Serie				Total
----			-----				-----
1592524800000000000	"Casos_activos"			35809
1592524800000000000	"Fallecidos"			4093
1592524800000000000	"Casos_totales"			231393
1592524800000000000	"Casos_recuperados_por_FIS"	191491
1592524800000000000	"Casos_recuperados_por_FD"	118406
1592524800000000000	"Casos_recuperados"		0
1592524800000000000	"Casos_nuevos_totales"		6290
1592524800000000000	"Casos_nuevos_sin_sintomas"	599
1592524800000000000	"Casos_nuevos_con_sintomas"	5016
1592524800000000000	"Casos_activos_por_FIS"		35809
1592524800000000000	"Casos_activos_por_FD"		108894

> select * from Totales_nacionales where time = '2020-06-20'

```

**Comment by pcornejov** [comment]
si claro, de hecho todos los productos que estoy consultando me llega la info hasta el 19 de junio..

La tengo en java, pero se entiende la query

InfluxDB influxDB = InfluxDBFactory.connect("http://covid19.dataobservatory.net:85/", "anonymous", "anonymous");
		String query = "Select * From autogen.Totales_nacionales";
		Query a = new Query(query, "covid19");

**Comment by pcornejov** [comment]
y los demas servicios que estoy consumiendo tambien pasa lo mismo, son los siguientes:

Totales_nacionales
Casos_confirmados_comunal
Fallecidos_cumulativo_regional
Casos_acumulados_regional
Casos_activos_comunal

porfa, para que le den una vuelta

**Comment by scornejob** [comment]
Gracias!

Ya detectamos el problema: esta relacionado a los archivos de MMA. En un rato vamos a tener todo actualizado.

**Comment by pcornejov** [comment]
Muchas gracias, estare atento

**Comment by scornejob** [comment]
```
> select * from Totales_nacionales where time >= '2020-06-22'
name: Totales_nacionales
time			Serie				Total
----			-----				-----
1592784000000000000	"Casos_activos"			37064
1592784000000000000	"Fallecidos"			4502
1592784000000000000	"Casos_totales"			246963
1592784000000000000	"Casos_recuperados_por_FIS"	205397
1592784000000000000	"Casos_recuperados_por_FD"	134344
1592784000000000000	"Casos_recuperados"		0
1592784000000000000	"Casos_nuevos_totales"		4608
1592784000000000000	"Casos_nuevos_sin_sintomas"	399
1592784000000000000	"Casos_nuevos_con_sintomas"	3710
1592784000000000000	"Casos_activos_por_FIS"		37064
1592784000000000000	"Casos_activos_por_FD"		108117

```
Listo @pcornejov . Puedes confirmar?

**Comment by pcornejov** [comment]
Estimados,
Al menos en los siguientes servicios si se refresco la data:
Totales_nacionales
Fallecidos_cumulativo_regional
Casos_acumulados_regional

A las 15 horas corre un proceso que tengo y podria verificar si se actualizaron tambien los siguientes:
Casos_confirmados_comunal
Casos_activos_comunal
