### ISSUE TITLE
data actualizada hasta el 27 de junio.

### ISSUE THREAD

**Issue by pcornejov** [Data-Observatory/covid19-API#18]

**Comment by scornejob** [comment]
El producto1 esta roto:
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto1/Covid-19_std.csv

**Comment by scornejob** [comment]
Tambien hay un problema con el producto 23:
`dateutil.parser._parser.ParserError: Unknown string format: Unnamed: 95`

**Comment by pcornejov** [comment]
cambian el formato de los codigos de comuna igual, de int a double.. para que tengan ojo jaja

**Comment by pcornejov** [comment]
el producto de totales_nacionales trae data hasta el 29, pero la API hasta el 27, tiene que ver con lo que dices?

**Comment by scornejob** [comment]
solucionado:
```
> select * from Casos_acumulados_regional where time >= '2020-06-30'
name: Casos_acumulados_regional
time			Casos_acumulados	Region
----			----------------	------
1593475200000000000	8829			"Antofagasta"
1593475200000000000	11752			"Valparaiso"
1593475200000000000	279393			"Total"
1593475200000000000	6049			"Tarapaca"
1593475200000000000	6081			"O'Higgins"
1593475200000000000	2397			"Nuble"
1593475200000000000	219151			"Metropolitana"
1593475200000000000	5549			"Maule"
1593475200000000000	1452			"Magallanes"
1593475200000000000	701			"Los_Rios"
1593475200000000000	1656			"Los_Lagos"
1593475200000000000	3050			"Coquimbo"
1593475200000000000	6697			"Biobio"
1593475200000000000	42			"Aysen"
1593475200000000000	1043			"Atacama"
1593475200000000000	1713			"Arica_y_Parinacota"
1593475200000000000	3231			"Araucania"
```

**Comment by pcornejov** [comment]
a las 5 corre mi proceso y confirmo si se actualizo la APi, aunque le acabo de hacer un select y me trae los totales nacionales hasta el 29 ahora

**Comment by scornejob** [comment]
Hola @pcornejov . Yo veo la data al dia. Puedes confirmar para cerrar este issue?

**Comment by pcornejov** [comment]
Totales_nacionales --> OK
Fallecidos_cumulativo_regional --> OK
Defunciones_comunales --> Data hasta el 28 de junio
Casos_confirmados_comunal --> Ya no trae data
Casos_acumulados_regional --> Ya no trae data
Casos_activos_comunal --> Ya no trae data

podrías revisar que paso con los que no traen data?

Saludos

**Comment by pcornejov** [comment]
algun comentario respecto a los informes que te comente que no traen data?

**Comment by fzmolina** [comment]
Estamos tratando de solucionarlo

**Comment by scornejob** [comment]
> select * from "Casos_acumulados_regional" where time >= '2020-07-02'
retorna.

> select * from "Defunciones_comunales" where time >= '2020-07-02'
no retorna

> select * from "Casos_confirmados_comunal" where time >= '2020-07-02'
no retorna

> select * from "Casos_activos_comunal" where time >= '2020-07-02'
no retorna

**Comment by fzmolina** [comment]
Hola @pcornejov ,

Hemos corregido el problema. Puedes confirmar que está OK para ti, porfa?

**Comment by pcornejov** [comment]
hola @fzmolina ,

Totales_nacionales --> data al 05/07
Fallecidos_cumulativo_regional --> data al 05/07
Defunciones_comunales --> data al 05/07
Casos_confirmados_comunal --> Ya no trae data
Casos_acumulados_regional --> Ya no trae data
Casos_activos_comunal --> Ya no trae data

Seguimos con problemas en los 3 ultimos.
Saludos

**Comment by fzmolina** [comment]
Gracias @pcornejov ,

Seguiremos buscando el origen de la falla. Gracias por mantenernos al tanto

**Comment by pcornejov** [comment]
@fzmolina de nada, avisa cuando corrijan para ejecutar una nueva prueba.

Saludos

**Comment by scornejob** [comment]
Hay algo en las fuentes:
Producto 1 MinCiencia:
```
SELECT LAST(*) FROM "Casos_confirmados_comunal"
name: Casos_confirmados_comunal
time			last_Casos_confirmados	last_Poblacion
----			----------------------	--------------
1970-01-01T00:00:00Z	302			35467
```

**Comment by scornejob** [comment]
Dejo este comentario aparte por que la fecha de estos productos me parece sospechosa (Defunciones y Nacimientos del Registro Civil)
Producto 31 MinCiencia:
```
> SELECT LAST(*) FROM "Nacimientos_comunal"
name: Nacimientos_comunal
time			last_Nacimientos
----			----------------
2020-07-04T00:00:00Z	1
```

Producto 32 MinCiencia:
```
> SELECT LAST(*) FROM "Defunciones_comunal"
name: Defunciones_comunal
time			last_Defunciones
----			----------------
2020-07-05T00:00:00Z	9
```

**Comment by fzmolina** [comment]
Es extraño ese input de los productos 1 y 2 del repo de MinCiencia. Estoy revisando la historia para localizar el problema

**Comment by fzmolina** [comment]
El release del informe EPI del 23 de Junio fue commiteado con hash: bc76ce61 en MinCiencia.

Ese release es el último que la API tomó bien. El siguiente release del informe EPI fue el 28 de Junio. El problema se da a partir del 27 de Junio

**Comment by scornejob** [comment]
El select last (*) retorna el inicio de la epoca:
https://github.com/influxdata/docs.influxdata.com/issues/1095

Voy a arreglar mis queries para sacar un valor representativo valido

**Comment by scornejob** [comment]
Actualice los queries y el [README.md](https://github.com/Data-Observatory/covid19-API): deje un query para el ultimo registro.
Los voy a revisar ahora, y si hay anomalias, posteo acá

**Comment by scornejob** [comment]
| Producto/Fecha |  "2020-07-07T00:00:00Z" |  "2020-07-05T00:00:00Z" |  "2020-06-28T00:00:00Z" | Otra|
|---|---|---|---|---|
| Producto 1	 |  | X |  |  |
| Producto 2 	 |  | X |  |  |
| Producto 3 	 | X  |  |  |  |
| Producto 4  	 |  |  |  |  |
| Producto 5  	 | X |  |  |  |
| Producto 6 	 |  |  |  |  |
| Producto 7	 | X |  |  |  |
| Producto 8	 | X |  |  |  |
| Producto 9	 | X |  |  |  |
| Producto 10	 | X |  |  |  |
| Producto 11	 |  |  |  |  |
| Producto 12	 |  |  |  |  |
| Producto 13	 | X |  |  |  |
| Producto 15	 |  |  | X  |  |
| Producto 16 	 |  | X |  |  |
| Producto 17	 | X |  |  |  |
| Producto 18 	 |  | X |  |  |
| Producto 19 	 |  | X |  |  |
| Producto 20 	 | X |  |  |  |
| Producto 21	  |  | X |  |  |
| Producto 22	  |  | X |  |  |
| Producto 23 	  | X  |  |  |  |
| Producto 24	  | X |  |  |  |
| Producto 25 	  |  | X |  |  |
| Producto 26	  | X |  |  |  |
| Producto 27	  | X |  |  |  |
| Producto 28	  |  |  | X |  |
| Producto 29	  |  |  |  |  |
| Producto 30 	  | X |  |  |  |
| Producto 31 	  | X |  |  |  |
| Producto 32  	  | X |  |  |  |
| Producto 33  	  |  |  |  | 2020-06-14T00:00:00Z |   
| Producto 34  	  |  |  |  |  | 
| Producto 35  	  |  | X |  |  |
| Producto 36  	  | X |  |  |  |
| Producto 37 	  |  | X |  |  |
| Producto 38 	  |  | X |  |  |
| Producto 39 	  |  |  |  | 2020-07-04T00:00:00Z |
| Producto 40 	  |  |  |  | 2020-06-01T00:00:00Z |
| Producto 41 	  |  |  |  | 2020-05-15T00:00:00Z | 
| Producto 42 	  |  |  |  | 2020-05-15T00:00:00Z |
| Producto 43  	  |  |  |  | 2020-06-29T23:00:00Z |	
| Producto 44 	  | X  |  |  |  |
| Producto 45 	  |  |  |  | 2020-06-28T00:00:00Z |

**Comment by fzmolina** [comment]
Hola!

Revisando: todos los que tienen actualización al 2020-07-07 deben tener la de hoy 2020-07-08. El DP14 no está en la tabla, debería tener la actualización de hoy.

Localizo dos posibles issues:

1) Los DP15 y DP45 tienen la misma estructura, puede ser un problema en el código de comuna en las comunas con tag "Desconocido". Yo arreglé los códigos de comuna para la última publicación, pero aún no para los release anteriores, por lo tanto, los *_HISTORICOS*.csv deben tener ese problema. 

2) Es probable que haya un problema similar con el DP28. Aunque este último tiene una estructura diferente al DP15 y DP45

Aparte: el DP39 tiene dos tipos de actualización, una diaria: Defunciones.csv, y una junto con el informe EPI: Defunciones_deis.csv

**Comment by pcornejov** [comment]
Totales_nacionales --> data al 08/07
Fallecidos_cumulativo_regional --> data al 08/07
Defunciones_comunales --> data al 08/07
Casos_confirmados_comunal --> Ya no trae data
Casos_acumulados_regional --> Ya no trae data
Casos_activos_comunal --> Ya no trae data

Seguimos con problemas en los 3 ultimos.
Saludos

**Comment by scornejob** [comment]
Gracias @pcornejov . Seguimos buscando el origen de la falla.

**Comment by scornejob** [comment]
Hola @pcornejov , 

Hace 10 minutos @fzmolina arreglo un asunto con los codigos regionales, y resulta que todo está al día:

**Casos_confirmados_comunal --> Ya no trae data** Yo veo data el [2020-07-05](http://covid19.dataobservatory.net:85/query?db=covid19&q=SELECT%20LAST(%22Casos_confirmados%22)%20FROM%20%22Casos_confirmados_comunal%22)
**Casos_acumulados_regional --> Ya no trae data** Yo veo data el [2020-07-08](http://covid19.dataobservatory.net:85/query?db=covid19&q=SELECT%20LAST(%22Casos_acumulados%22)%20FROM%20%22Casos_acumulados_regional%22)
**Casos_activos_comunal --> Ya no trae data** Yo veo data el [2020-07-05}(http://covid19.dataobservatory.net:85/query?db=covid19&q=SELECT%20LAST(%22Casos_activos%22)%20FROM%20%22Casos_activos_comunal%22)

Cabe mencionar que Casos_confirmados_comunal y Casos_confirmados_comunal se extraen del informe epidemiologico, por lo tanto se actualizan cada dos o tres dias, mientras Casos_acumulados_regional es del reporte diario, asi que se actualiza con esa frecuencia.

Nos confirmas que est bien lo que ves?

Y dicho sea de paso, descubrimos un problema similar con el producto 28, que vamos a reparar.

**Comment by pcornejov** [comment]
pero cambiaste la consulta o algo?.. yo hago esto en la consola y no me trae nada..

> pcornejov@M2200ISP-PCORNE MINGW64 /
$ curl -u anonymous:anonymous 'http://covid19.dataobservatory.net:85/query?db=covid19' --data-urlencode "q=SELECT "Total" FROM "autogen"."Casos_activos_comunal" "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    75    0    17  100    58     38    131 --:--:-- --:--:-- --:--:--   170{"results":[{}]}

**Comment by scornejob** [comment]
Hola @pcornejov:

No, no he cambiado la query, pero me llama la atencion tu "total", la query deberia ser asi:
`curl -u anonymous:anonymous 'http://covid19.dataobservatory.net:85/query?db=covid19' --data-urlencode "q=SELECT "Casos_activos" FROM "autogen"."Casos_activos_comunal" "`

y para confirmados:
`curl -u anonymous:anonymous 'http://covid19.dataobservatory.net:85/query?db=covid19' --data-urlencode "q=SELECT "Casos_confirmados" FROM "autogen"."Casos_confirmados_comunal" "`

No recuerdo que hayamos cambiado las el nombre de los campos, pero voy a revisar la historia en GIT

**Comment by scornejob** [comment]
Hola @pcornejov .

[Este es el código de hace 29 dias](https://github.com/Data-Observatory/covid19-API/blob/61cc8ca594516d4ecbbf9fe5ffe3fa286e895a9b/src/minCiencia2Influx.py), y los nombres de los campos no han cambiado. Puedes probar con las queries que puse arriba?

**Comment by pcornejov** [comment]
$ $ curl -u anonymous:anonymous 'http://covid19.dataobservatory.net:85/query?db=covid19' --data-urlencode "q=SELECT "Total" FROM "autogen"."Casos_activos_comunal" "
la consulta es esa, el total es la respuesta que te da y se corrio el cursor cuando copie la respuesta de la consola

**Comment by pcornejov** [comment]
lo siento mucho, tenia mal guardada la query en la consola.. pero en mi aplicativo no se actualiza, veré que pasa por que ahora hice un select * y si me trae data.

Gracias

**Comment by scornejob** [comment]
@pcornejov , no hay problema! encontramos otros errores tambien, asi que el issue nos sirvio para eso.
Lo reabri por que esta pendiente el prod28

**Comment by pcornejov** [comment]
dale, validando al final era mi aplicativo el que tenia una pifia.. gracias por todo.

**Comment by scornejob** [comment]
Ahora entendimos el "problema" con el prod 28: sus fechas corresponden a las semanas epidemiologicas, y los ultimos datos son de la semana epidemiologica 27, que empezo el 28 de Junio. Asi que cerramos finalemente este issue.
