### ISSUE TITLE
formato Totales_nacionales como regional y comunal

### ISSUE THREAD

**Issue by pcornejov** [Data-Observatory/covid19-API#9]
Estimados,

Es posible que disponibilicen la misma data que sale para el producto Totales_nacionales pero para las regiones y comunas del país?

La idea seria tener la misma data para los 3 productos.

Saludos

**Comment by MinCiencia** [comment]
Hola @pcornejov, parcialmente porque los fallecidos por COVID19 no se publican a nivel comunal, y los activos (y recuperados) se publican solo 2 veces por semana a nivel comunal.

**Comment by pcornejov** [comment]
Pero entonce se podría tener a nivel regional?.. y a nivel comunal de forma parcial (no incluyendo los fallecidos) actualizados a el ultimo momento que ustedes tengan data?, la idea es poder plasmar la información en un mapa de Chile con idealmente los mismos parámetros, tanto para nacional, regional y comunal
